-- migrations/2026-07-15_b7_financial_ledger_foundation.sql
-- Access Control V2 / B7A1 — additive financial-ledger foundation (schema only).
-- TARGET PROJECT REF: tdikhfeinufaahagmpjz   ***STAGING ONLY***
-- Creates public.order_financial_events (immutable, append-only) + its append-only
-- trigger, RLS (zero policies) and service_role SELECT/INSERT grants; adds three
-- additive columns (ordenes.refunded, manual_giros.assigned_actor,
-- auth_actors.active_manual_giro_id). NO business RPC, NO wiring, NO data mutation.
-- Fail-closed on partial pre-existing B7A1 objects (no permissive IF NOT EXISTS on
-- the ledger). NOT APPLIED — unwired, staging-only.
--
-- Locked idempotency/digest contract (implemented later in B7A2, NOT here):
--   payload_digest = lowercase sha256 hex over canonical, server-derived semantics
--   (order_id, type, idem_scope_key, by_actor, by_role, normalized reason,
--    prev_estado, new_estado, prev_pay_state, new_pay_state, + per-type amount/
--    payment_method/legacy/basis-uuid/original_giro_id). Excludes ip_hash, meta,
--   created_at, transport/display fields. Caller supplies ONLY idem_scope_key;
--   never p_digest. A different normalized mandatory reason under the same scope
--   key is a canonical-digest change → idempotency CONFLICT (never a silent reuse).
BEGIN;

-- Staging-positive guard (same sentinel as B0/B2/B5/B6).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM supabase_migrations.schema_migrations WHERE version='20260710075612')
  THEN RAISE EXCEPTION 'B7A1 refused: staging sentinel migration absent — wrong database?'; END IF;
END $$;

-- Fail-closed guard: refuse if ANY B7A1 object already exists (no silent drift).
DO $$
BEGIN
  IF to_regclass('public.order_financial_events') IS NOT NULL
     OR EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
                WHERE n.nspname='public' AND p.proname='order_financial_events_append_only')
     OR EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name='ordenes' AND column_name='refunded')
     OR EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name='manual_giros' AND column_name='assigned_actor')
     OR EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_schema='public' AND table_name='auth_actors' AND column_name='active_manual_giro_id')
  THEN RAISE EXCEPTION 'B7A1 refused: partial B7A1 objects already present — resolve drift first.'; END IF;
END $$;

-- ── immutable financial ledger ───────────────────────────────────────────────
CREATE TABLE public.order_financial_events (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id         text NOT NULL,
  type             text NOT NULL,
  amount           numeric(10,2) NOT NULL,
  payment_method   text,
  reason           text,
  legacy           boolean NOT NULL DEFAULT false,
  by_actor         text NOT NULL,
  by_role          text NOT NULL,
  prev_estado      text,
  new_estado       text,
  prev_pay_state   text NOT NULL,
  new_pay_state    text NOT NULL,
  original_giro_id text,                       -- immutable historical snapshot; NO FK
  ip_hash          text,
  meta             jsonb NOT NULL DEFAULT '{}'::jsonb,
  idem_scope_key   text NOT NULL,
  payload_digest   text NOT NULL,              -- generated by B7A2 RPC, never by caller
  created_at       timestamptz NOT NULL DEFAULT now(),

  constraint ofe_order_id_fk foreign key (order_id)
    references public.ordenes(id) on delete restrict,
  constraint ofe_by_actor_fk foreign key (by_actor)
    references public.auth_actors(actor) on delete restrict,

  constraint ofe_type_chk check (type in ('payment','refund','void','payment_imported')),
  constraint ofe_amount_chk check (
    (type = 'void' and amount = 0) or (type <> 'void' and amount > 0)),
  constraint ofe_payment_method_chk check (
    (type = 'void' and payment_method is null) or
    (type in ('payment','payment_imported','refund') and payment_method in ('efectivo','tarjeta','bizum'))),
  constraint ofe_legacy_chk check (
    (type = 'payment_imported' and legacy = true) or (type <> 'payment_imported' and legacy = false)),
  constraint ofe_original_giro_chk check (
    type = 'void' or original_giro_id is null),
  constraint ofe_reason_chk check (
    (type = 'payment' and (reason is null or btrim(reason) <> '')) or
    (type in ('refund','void','payment_imported') and reason is not null and btrim(reason) <> '')),
  constraint ofe_by_actor_chk check (by_actor in ('owner','operator_primary','operator_backup','rider')),
  constraint ofe_by_role_chk check (by_role in ('admin','operator','rider')),
  constraint ofe_actor_role_map_chk check (
    (by_actor='owner'            and by_role='admin')    or
    (by_actor='operator_primary' and by_role='operator') or
    (by_actor='operator_backup'  and by_role='operator') or
    (by_actor='rider'            and by_role='rider')),
  constraint ofe_prev_pay_state_chk check (prev_pay_state in ('unpaid','paid','refunded')),
  constraint ofe_new_pay_state_chk check (new_pay_state in ('unpaid','paid','refunded')),
  constraint ofe_pay_state_transition_chk check (
    (type='payment'          and prev_pay_state='unpaid' and new_pay_state='paid')     or
    (type='payment_imported' and prev_pay_state='unpaid' and new_pay_state='paid')     or
    (type='refund'           and prev_pay_state='paid'   and new_pay_state='refunded') or
    (type='void'             and prev_pay_state = new_pay_state)),
  constraint ofe_ip_hash_chk check (
    ip_hash is null or (btrim(ip_hash) <> '' and length(ip_hash) <= 64)),
  constraint ofe_meta_chk check (jsonb_typeof(meta) = 'object' and length(meta::text) <= 2048),
  constraint ofe_idem_scope_key_chk check (
    char_length(idem_scope_key) between 8 and 128 and idem_scope_key ~ '^[A-Za-z0-9_-]+$'),
  constraint ofe_payload_digest_chk check (payload_digest ~ '^[0-9a-f]{64}$'),

  constraint order_financial_events_scope_uq unique (order_id, type, idem_scope_key)
);

-- one payment basis per order / one refund per order
CREATE UNIQUE INDEX order_financial_events_one_payment_uq
  ON public.order_financial_events (order_id) WHERE type in ('payment','payment_imported');
CREATE UNIQUE INDEX order_financial_events_one_refund_uq
  ON public.order_financial_events (order_id) WHERE type = 'refund';
-- history lookup
CREATE INDEX order_financial_events_order_created_idx
  ON public.order_financial_events (order_id, created_at);

-- ── append-only enforcement (infrastructure trigger, NOT a routed RPC) ───────
CREATE OR REPLACE FUNCTION public.order_financial_events_append_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $fn$
BEGIN
  -- deterministic, no dynamic SQL, no row contents leaked
  RAISE EXCEPTION 'order_financial_events is append-only' USING ERRCODE='0A000';
END;
$fn$;
REVOKE ALL ON FUNCTION public.order_financial_events_append_only() FROM PUBLIC, anon, authenticated;

CREATE TRIGGER order_financial_events_no_update_delete
  BEFORE UPDATE OR DELETE ON public.order_financial_events
  FOR EACH ROW EXECUTE FUNCTION public.order_financial_events_append_only();

-- ── RLS (zero policies) + minimal service_role grants ────────────────────────
ALTER TABLE public.order_financial_events ENABLE ROW LEVEL SECURITY;
-- ZERO CREATE POLICY -> default-deny for anon & authenticated; service_role bypass.
REVOKE ALL ON public.order_financial_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.order_financial_events TO service_role;   -- no UPDATE/DELETE/TRUNCATE/REFERENCES/TRIGGER

comment on table public.order_financial_events is
  'B7 immutable financial ledger; append-only (trigger + no update/delete grant); service_role SELECT/INSERT only.';

-- ── additive order marker (UI/read convenience only; never money authority) ──
ALTER TABLE public.ordenes ADD COLUMN refunded boolean NOT NULL DEFAULT false;

-- ── giro ownership (additive) ────────────────────────────────────────────────
ALTER TABLE public.manual_giros
  ADD COLUMN assigned_actor text
    REFERENCES public.auth_actors(actor) ON DELETE RESTRICT;
ALTER TABLE public.manual_giros
  ADD CONSTRAINT manual_giros_assigned_actor_chk
    CHECK (assigned_actor IS NULL OR assigned_actor = 'rider');
-- one non-dissolved active giro per rider
CREATE UNIQUE INDEX manual_giros_assigned_actor_active_uq
  ON public.manual_giros (assigned_actor)
  WHERE assigned_actor IS NOT NULL AND dissolved_at IS NULL;

ALTER TABLE public.auth_actors
  ADD COLUMN active_manual_giro_id text
    REFERENCES public.manual_giros(id) ON DELETE SET NULL;
ALTER TABLE public.auth_actors
  ADD CONSTRAINT auth_actors_active_giro_role_chk
    CHECK (active_manual_giro_id IS NULL OR role = 'rider');

COMMIT;
