-- ===============================================================
-- 2026-05-25 — manual_giros (P1C.1 of DELIVERY-MANUAL-GIRO-01)
-- ===============================================================
-- Adds a persistent representation of operator-defined manual delivery
-- giros. Successor of the volatile UI-only prototype (P1A, commit
-- a8f97da on the frontend repo). Data contract approved 2026-05-25
-- (Option C: dedicated table + denormalized FK on ordenes).
--
-- Scope of this migration:
--   - new table public.manual_giros (id, seq, giro_day, audit cols)
--   - new column public.ordenes.manual_giro_id (nullable, soft FK)
--   - two partial indexes for the hot lookup paths
--
-- Out of scope for this migration (P1C.1):
--   - forno_out aggregation. Q4 is BLOCKED, see
--     LaDieciBotV2_DELIVERY_MANUAL_GIRO_01BC_SPEC.md §13. P1C.2 only.
--   - storico schema changes. Manual giros are intentionally NOT
--     propagated to public.storico (audit lives in manual_giros).
--   - Cocina UI. Out of scope until P1D.
--   - ETA/training. manual_giro_id MUST be excluded from any future
--     training query, see SPEC §14.
--
-- Apply manually via Supabase SQL editor (project: LaDieci10App,
-- ref wnswassgfuuivmfwjxsf). No migration framework in use.
-- Rollback statements at the bottom of this file (commented).
-- ===============================================================


-- 1) Table manual_giros
--
-- id format: mg_<yymmdd>_<seq> (e.g. mg_260525_3). Generated by the
-- backend, not by the DB. Readable in logs and naturally scoped by day.
--
-- seq:      per-day counter (Madrid TZ). Reset is logical, not a DDL
--           sequence: backend computes COALESCE(MAX(seq),0)+1 for the
--           current giro_day, protected by the UNIQUE constraint below.
--
-- giro_day: date derived by the backend from created_at in
--           Europe/Madrid timezone. Stored explicitly to make the
--           UNIQUE (giro_day, seq) constraint exact and to keep
--           per-day queries trivial (no AT TIME ZONE in hot paths).
--
-- created_by: text NULL. NO DEFAULT in the DB on purpose. We do not
--             want a fake-looking default written by the database
--             itself. The backend passes an explicit placeholder
--             (currently 'pin_dashboard', since per-operator login is
--             not in place yet — see SPEC §20 Q3). When per-operator
--             login lands, the backend starts writing the real
--             identifier without any schema change.
--
-- dissolved_at: soft-delete marker. We never hard-delete from this
--               table; audit value is preserved across services.

CREATE TABLE IF NOT EXISTS public.manual_giros (
  id           text        PRIMARY KEY,
  seq          int         NOT NULL,
  giro_day     date        NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  created_by   text        NULL,
  dissolved_at timestamptz NULL,
  CONSTRAINT manual_giros_day_seq_unique UNIQUE (giro_day, seq)
);

-- Partial index for the hot lookup "active giros today" performed by
-- the backend GET getManualGiros endpoint.
CREATE INDEX IF NOT EXISTS idx_manual_giros_active
  ON public.manual_giros (giro_day)
  WHERE dissolved_at IS NULL;


-- 2) Column ordenes.manual_giro_id
--
-- Nullable on purpose: old frontend builds (pre-P1C.1) keep working,
-- they simply ignore the column. Rollback is trivial.
--
-- Soft foreign key: FK with ON DELETE SET NULL is a safety net. Normal
-- flow uses soft-delete on manual_giros (dissolved_at), so the FK is
-- only exercised if someone hard-deletes a giro by mistake — in that
-- case orphaned ordenes get NULL'd instead of pointing at nothing.

ALTER TABLE public.ordenes
  ADD COLUMN IF NOT EXISTS manual_giro_id text NULL;

ALTER TABLE public.ordenes
  ADD CONSTRAINT ordenes_manual_giro_id_fkey
  FOREIGN KEY (manual_giro_id)
  REFERENCES public.manual_giros(id)
  ON DELETE SET NULL;

-- Partial index for the auto-dissolve count check
--   SELECT COUNT(*) FROM ordenes
--   WHERE manual_giro_id = $1 AND estado IN (EN_COCINA, LISTO, EN_ENTREGA)
-- and for the Entregas render group-by.
CREATE INDEX IF NOT EXISTS idx_ordenes_manual_giro_id
  ON public.ordenes (manual_giro_id)
  WHERE manual_giro_id IS NOT NULL;


-- 3) Access policy — RLS NOTE
--
-- public.manual_giros is NOT designed for direct frontend anon access.
-- Reads and writes are expected to go through the backend (Railway,
-- service_role key, authenticated with X-Api-Key at the API gateway).
--
-- This migration intentionally does NOT create RLS policies on
-- manual_giros. The frontend will obtain giro metadata via a backend
-- proxy endpoint (api.getManualGiros → backend getManualGiros action),
-- not via the anon Supabase client.
--
-- If a future need to expose manual_giros directly to the anon client
-- arises, a dedicated RLS evaluation must be done first:
--   - decide if SELECT-only or read+write
--   - decide if rows are visible across services/days
--   - decide if dissolved giros are hidden
-- Default policy of Supabase with RLS enabled is "deny" — which is the
-- safe behavior for now.
--
-- For public.ordenes the existing RLS configuration is unchanged by
-- this migration. The new manual_giro_id column inherits the same
-- row visibility as the rest of the ordenes row.


-- ===============================================================
-- Rollback (commented — apply manually if needed)
-- ===============================================================
--
-- ALTER TABLE public.ordenes
--   DROP CONSTRAINT IF EXISTS ordenes_manual_giro_id_fkey;
-- DROP INDEX IF EXISTS public.idx_ordenes_manual_giro_id;
-- ALTER TABLE public.ordenes DROP COLUMN IF EXISTS manual_giro_id;
--
-- DROP INDEX IF EXISTS public.idx_manual_giros_active;
-- DROP TABLE IF EXISTS public.manual_giros;
--
-- Rollback is safe at any time as long as no row in ordenes has
-- manual_giro_id IS NOT NULL: ON DELETE SET NULL handles orphaning
-- even if the table is dropped before the column.
