-- S4 — BOOTSTRAP SEED for public.ladieci_schema_migrations
-- Authority: MESA_REMEDIATION_PLAN_FINAL_V2_1_2_2026-08-15.md, slice S4,
-- §15: "HISTORICAL METHOD: one-off seeding from the manifest using the S0
-- §K classification. Nothing is asserted that was not proven."
--
-- PAIRED with 2026-08-15_s4_ladieci_schema_migrations_ledger.sql (must run
-- after it -- separate transaction, per §15: "table + trigger + REVOKE/RLS
-- in one transaction; bootstrap seeding in a second").
--
-- SOURCE OF TRUTH: ops/baseline/mesa_baseline_2026-08-15.json, section_K
-- (70 rows, frozen at S0: 36 verified / 34 bootstrapped_unverified, produced
-- by matching each manifest filename's slug against the live, READ-ONLY-
-- inspected supabase_migrations.schema_migrations.name -- exact match only,
-- no fuzzy inference), PLUS manifest rows 71-73 (created after S0 by S1/S2
-- of this same remediation, classified by applying the IDENTICAL mechanical
-- method against the live ledger, re-verified in this slice's own Phase 0/1,
-- not merely assumed from the frozen S0 artifact which only covers 1-70).
-- 73 rows total: 38 verified, 35 bootstrapped_unverified.
--
-- All 73 rows get kind='bootstrap' -- by construction, per §15's own
-- compatibility rule ("REQUIRED_MIGRATIONS, containing only post-epoch
-- (kind <> 'bootstrap') filenames"): everything seeded here predates the
-- ledger's own existence and is therefore pre-epoch history, never a
-- candidate for a future release's REQUIRED_MIGRATIONS declaration.
--
-- TWO DATA-QUALITY GAPS FOUND AND CORRECTED WHILE BUILDING THIS SEED (both
-- flagged in the affected rows' own notes column, not hidden):
--
--   1. CHECKSUM (5 rows: apply_order 51, 52, 53, 55, 63). The S0 §K JSON
--      artifact recorded either the literal placeholder text
--      "(local draft, not yet committed)" or (row 63) an 18-character value
--      with 2 extra trailing characters -- neither satisfies this table's
--      checksum_sha256 CHECK (~ '^[0-9a-f]{16}$'), and neither was ever a
--      real checksum in the first place (a pre-existing manifest-generation
--      gap, unrelated to S4). Recomputed first-party via sha256 of the
--      exact currently-committed migration file (verified against a clean
--      working tree at backend HEAD 4dd4034) -- MORE proof than the stale
--      artifact had, not an unproven assertion. Row 63's recomputed value
--      matches the JSON's own first 16 characters exactly, confirming that
--      one was a transcription artifact, not a real discrepancy.
--
--   2. APPLIED_BY (21 rows). The manifest's own "commit" column was never
--      retroactively filled in for these rows and still holds
--      authoring-time placeholder text ('pending', 'applied', '(local, not
--      yet committed)', etc). Seeding literal "pending" as applied_by into
--      a ledger whose own GOAL is "semantically truthful from day one"
--      would defeat the point of building it. Resolved first-party via
--      `git log --diff-filter=A --format=%h -- migrations/<file>` against
--      the actual committed backend history -- the same class of evidence
--      already used throughout S1-S3 of this remediation.
--
-- Neither correction touches any migration FILE's content (the "no
-- historical migration rewrites" prohibition is about file contents, not
-- this table's own metadata) and neither reopens S0-S3 architecture or
-- reclassifies any row's verification_status -- both were already fixed
-- points from the frozen S0 §K evidence; only the checksum/applied_by
-- VALUES needed real data where the source artifacts had none.
--
-- IDEMPOTENCY: INSERT ... ON CONFLICT (filename) DO NOTHING -- a re-run
-- inserts zero rows.
--
-- ABSOLUTE OWNERSHIP BOUNDARY: this migration only ever SELECTs from
-- supabase_migrations.schema_migrations (read-only evidence, already
-- consumed at authoring time to produce the S0 §K classification baked
-- into the VALUES below) and only ever INSERTs into
-- public.ladieci_schema_migrations. It never writes to any Supabase-owned
-- migration-history table.

-- ── Predecessor guard ────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relname = 'ladieci_schema_migrations'
  ) THEN
    RAISE EXCEPTION 'S4 bootstrap-seed refused: public.ladieci_schema_migrations does not exist -- apply 2026-08-15_s4_ladieci_schema_migrations_ledger.sql first';
  END IF;
END $$;

-- ── The seed ─────────────────────────────────────────────────────────────
INSERT INTO public.ladieci_schema_migrations
  (filename, checksum_sha256, apply_order, kind, verification_status,
   applied_at, applied_by, verified_at, verified_by, verification_method, notes)
VALUES
  ('2026-05-14_geo_cache_confidence.sql', '598f1f38caffe541', 1, 'bootstrap', 'bootstrapped_unverified', '2026-05-14 00:00:00+00'::timestamptz, 'fab25bc', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-05-25_manual_giros.sql', '46c748f218f411cb', 2, 'bootstrap', 'bootstrapped_unverified', '2026-05-25 00:00:00+00'::timestamptz, 'cfba8b9', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-05-29_manual_giros_entrega_ref.sql', '352741f5ad731f19', 3, 'bootstrap', 'bootstrapped_unverified', '2026-05-29 00:00:00+00'::timestamptz, '3061989', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-05-29_manual_giros_hora_ref.sql', '444f31d91d9b14ac', 4, 'bootstrap', 'bootstrapped_unverified', '2026-05-29 00:00:00+00'::timestamptz, '9edcdb9', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-06-02_driver_schedule_fields.sql', '36a1447f9e69cc51', 5, 'bootstrap', 'bootstrapped_unverified', '2026-06-02 00:00:00+00'::timestamptz, '5f7f31d', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-06-05_order_state_transition_logs.sql', '6a80a260b9a7e77c', 6, 'bootstrap', 'bootstrapped_unverified', '2026-06-05 00:00:00+00'::timestamptz, '5d9e2de', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-10_p0_lock_sensitive_reads.sql', '69fdb47bda938354', 7, 'bootstrap', 'bootstrapped_unverified', '2026-07-10 00:00:00+00'::timestamptz, '3e0814c', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-13_auth_active_events.sql', 'a2ca58a671383c12', 8, 'bootstrap', 'verified', '2026-07-14 00:00:00+00'::timestamptz, '3888d22', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-13_auth_rpc.sql', '7e9a6ce04f5b7290', 9, 'bootstrap', 'verified', '2026-07-13 00:00:00+00'::timestamptz, 'eaad05b', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-13_auth_v2_foundation.sql', '9af802a1c54ae7c1', 10, 'bootstrap', 'verified', '2026-07-13 00:00:00+00'::timestamptz, '1fef81d', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-14_auth_recovery_windows.sql', '61b7fece50873718', 11, 'bootstrap', 'verified', '2026-07-15 00:00:00+00'::timestamptz, '8a1a4ff', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_auth_admin_access_management.sql', 'c18838668c3d3219', 12, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, '785d317', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_auth_unlocked_event.sql', '4728a8de17371a94', 13, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, '15512c9', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_b7_financial_ledger_foundation.sql', 'f9f51b24f32c331e', 14, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, '93861d8', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_b7_financial_ledger_grant_hardening.sql', 'a783b8d57b01abde', 15, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, '2955c27', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_b7_payment_basis_rpcs.sql', '53f572f8fa61a557', 16, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, '700c03b', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-15_b7_refund_void_rpcs.sql', 'bebb7de415c20d23', 17, 'bootstrap', 'bootstrapped_unverified', '2026-07-15 00:00:00+00'::timestamptz, 'e72218a', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-16_b7_void_digest_replay_fix.sql', '4021e40294324feb', 18, 'bootstrap', 'bootstrapped_unverified', '2026-07-16 00:00:00+00'::timestamptz, 'aca5969', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-17_b7_financial_session_version_guard.sql', 'f3d56d58b834ce72', 19, 'bootstrap', 'bootstrapped_unverified', '2026-07-17 00:00:00+00'::timestamptz, 'a5ef761', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-19_b7_payment_basis_historical_replay_fix.sql', '8707762a27ab5f99', 20, 'bootstrap', 'bootstrapped_unverified', '2026-07-19 00:00:00+00'::timestamptz, '2ec5246', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-20_config_write_revoke.sql', 'b46a6bdeac02022c', 21, 'bootstrap', 'bootstrapped_unverified', '2026-07-20 00:00:00+00'::timestamptz, '573398b', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-20_manual_giros_rls_lockdown.sql', '1cf173b97249f40b', 22, 'bootstrap', 'bootstrapped_unverified', '2026-07-20 00:00:00+00'::timestamptz, '573398b', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-20_rider_trip_rpcs.sql', '450c5d75edf210b8', 23, 'bootstrap', 'bootstrapped_unverified', '2026-07-20 00:00:00+00'::timestamptz, '77693e9', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-21_fix_rider_delivery_log_timestamps.sql', 'bec2490d9d32e56e', 24, 'bootstrap', 'bootstrapped_unverified', '2026-07-21 00:00:00+00'::timestamptz, '9fef8d3', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-21_fix_rider_trip_json_null_idempotency.sql', '73d4b2fa60cc6925', 25, 'bootstrap', 'bootstrapped_unverified', '2026-07-21 00:00:00+00'::timestamptz, '821d56b', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-22_service_session_identity.sql', '835d9d6d0fa7d971', 26, 'bootstrap', 'verified', '2026-07-22 00:00:00+00'::timestamptz, '207672b', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-07-23_storico_drop_legacy_orden_fecha_uniqueness.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-07-23_storico_drop_legacy_orden_fecha_uniqueness.sql', '993ab0c39e842814', 27, 'bootstrap', 'verified', '2026-07-23 00:00:00+00'::timestamptz, '0cf9320', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-07-23_storico_session_order_uq_nonpartial.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-07-23_storico_session_order_uq_nonpartial.sql', 'a074088c269073e0', 28, 'bootstrap', 'verified', '2026-07-23 00:00:00+00'::timestamptz, '4ecf3e1', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-24_workspace_foundation.sql', '42c949a39ce7d34d', 29, 'bootstrap', 'verified', '2026-07-23 00:00:00+00'::timestamptz, '140c8cd', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-24_account_auth_boundary.sql', 'c46be5b362fa6541', 30, 'bootstrap', 'verified', '2026-07-23 00:00:00+00'::timestamptz, '0222f04', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-24_workspace_owner_pin.sql', 'e5c02d93520ee665', 31, 'bootstrap', 'bootstrapped_unverified', '2026-07-24 00:00:00+00'::timestamptz, 'bd6f363', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-25_canonical_pin_rotation.sql', 'bfa0711f14dde6be', 32, 'bootstrap', 'verified', '2026-07-25 00:00:00+00'::timestamptz, 'f54d6e7', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-26_disable_legacy_pin_rotation.sql', '510ab39362dd4ff7', 33, 'bootstrap', 'verified', '2026-07-26 00:00:00+00'::timestamptz, 'f54d6e7', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-26_two_service_identity.sql', '3027d7291d3c6c6d', 34, 'bootstrap', 'bootstrapped_unverified', '2026-07-26 00:00:00+00'::timestamptz, '9a86fb1', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-27_order_state_logs_session_identity.sql', 'f1448c0f33ef8bad', 35, 'bootstrap', 'bootstrapped_unverified', '2026-07-27 00:00:00+00'::timestamptz, 'e32ef8f', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-27_s2_7d6e3a_rider_ledger_writer_additive.sql', '2c0796cc34aaa546', 36, 'bootstrap', 'verified', '2026-07-27 00:00:00+00'::timestamptz, 'a043872', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-27_s2_7d6e3d_retire_complete_rider_stop.sql', '5766f9eebe9c1cee', 37, 'bootstrap', 'bootstrapped_unverified', '2026-07-27 00:00:00+00'::timestamptz, 'b834cc6', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-28_service_order_number.sql', '18e91cd253cbad04', 38, 'bootstrap', 'verified', '2026-07-28 00:00:00+00'::timestamptz, '846a58f', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-29_v3a_access_control_foundation.sql', '4d3aae1ea98ba87c', 39, 'bootstrap', 'verified', '2026-07-29 00:00:00+00'::timestamptz, 'd3610ae', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-29_v3b_auth_set_actor_pin_v3.sql', 'f2e887c6dce6abe4', 40, 'bootstrap', 'verified', '2026-07-29 00:00:00+00'::timestamptz, 'f75a8f4', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-29_v3c_auth_change_actor_role.sql', '0825d580cc96eb10', 41, 'bootstrap', 'verified', '2026-07-29 00:00:00+00'::timestamptz, '35344f3', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-29_v3d_dynamic_access_user.sql', 'c64249995bbf4fbd', 42, 'bootstrap', 'verified', '2026-07-30 00:00:00+00'::timestamptz, 'd8cfc96', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-30_v3e_access_user_lifecycle.sql', 'cb570e3d738f2aeb', 43, 'bootstrap', 'verified', '2026-07-30 00:00:00+00'::timestamptz, 'd544f72', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-07-31_v3g_waiter_table_assignment_safety.sql', '4956087056f1a299', 44, 'bootstrap', 'verified', '2026-07-31 00:00:00+00'::timestamptz, '5c8d12e', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-08-01_v3h_messa_billing_foundation.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-08-01_v3h_messa_billing_foundation.sql', '9ed5d790049bc270', 45, 'bootstrap', 'verified', '2026-08-01 00:00:00+00'::timestamptz, 'aeab2ff', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-08-01_v3h1_messa_fk_indexes.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-08-01_v3h1_messa_fk_indexes.sql', 'd16fc57267c0bd98', 46, 'bootstrap', 'verified', '2026-08-01 00:00:00+00'::timestamptz, '1505250', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-08-01_v3h1a_messa_payment_digest_path.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-08-01_v3h1a_messa_payment_digest_path.sql', '97a4e11977d43313', 47, 'bootstrap', 'verified', '2026-08-01 00:00:00+00'::timestamptz, '58dd10c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  -- language-guard: allow-legacy the filename below is an existing, already-committed historical migration filename (2026-08-01_v3h2_messa_reservations.sql) quoted verbatim as bootstrap data, not new vocabulary
  ('2026-08-01_v3h2_messa_reservations.sql', 'b2d165b1d97f9c8c', 48, 'bootstrap', 'bootstrapped_unverified', '2026-08-01 00:00:00+00'::timestamptz, 'e3e90ad', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-02_service_close_live_work_guard.sql', 'c036a2ceab7414bc', 49, 'bootstrap', 'bootstrapped_unverified', '2026-08-02 00:00:00+00'::timestamptz, 'a43dbb5', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-02_v3i_mesa_covers_deferred.sql', 'bdd5807446fbce55', 50, 'bootstrap', 'verified', '2026-08-02 00:00:00+00'::timestamptz, 'b97194c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-02_v3j_mesa_nomenclature_cutover.sql', '068c094f1d32321e', 51, 'bootstrap', 'verified', '2026-08-02 00:00:00+00'::timestamptz, 'b97194c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | S0 §K JSON recorded the placeholder "(local draft, not yet committed)" instead of a real checksum (stale artifact -- the file has been committed since b97194c). Recomputed first-party via sha256 of the exact currently-committed file. | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-02_v3k_mesa_table_shapes.sql', 'ade983b716650902', 52, 'bootstrap', 'verified', '2026-08-02 00:00:00+00'::timestamptz, 'b97194c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | S0 §K JSON recorded the placeholder "(local draft, not yet committed)" instead of a real checksum (stale artifact -- the file has been committed since b97194c). Recomputed first-party via sha256 of the exact currently-committed file. | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-08_service_closeout_incidents_foundation.sql', 'a314fdf4052f5f2b', 53, 'bootstrap', 'verified', '2026-08-08 00:00:00+00'::timestamptz, '47d023d', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | S0 §K JSON recorded the placeholder "(local draft, not yet committed)" instead of a real checksum (stale artifact -- the file has been committed since a95e72f). Recomputed first-party via sha256 of the exact currently-committed file. | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-08_service_closeout_post_close_financial_resolutions.sql', 'eebf5ed95d15b5c9', 54, 'bootstrap', 'verified', '2026-08-08 00:00:00+00'::timestamptz, '21fef2d', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-08_service_closeout_attempt_ownership.sql', '13600d8d68d686a0', 55, 'bootstrap', 'verified', '2026-08-08 00:00:00+00'::timestamptz, '0fef282', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | S0 §K JSON recorded the placeholder "(local draft, not yet committed)" instead of a real checksum (stale artifact -- the file has been committed since a95e72f). Recomputed first-party via sha256 of the exact currently-committed file. | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_closeout_cross_service_table_policy.sql', 'ce409a48f88904dc', 56, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '1400aa5', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | manifest recorded applied_by as "pending" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_foundation.sql', 'cf2d1699527828b4', 57, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '4252241', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_close_engine.sql', '1246fd5abf816520', 58, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '5152055', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_close_ownership_hardening.sql', '69366f98d4d234c6', 59, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '77279d6', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_incident_policy.sql', '320fd694de9129d7', 61, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '49c4839', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_table_release.sql', 'ba2690b78a7be07f', 60, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '78ff66d', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-09_service_lifecycle_v3_rollover.sql', '473c8b651321c6c8', 62, 'bootstrap', 'bootstrapped_unverified', '2026-08-09 00:00:00+00'::timestamptz, '78ff66d', NULL, NULL, NULL, 'no independent ledger record; applied manually or under a different ledger name | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-10_mesa_close_forces_orphaned_orders.sql', 'dc6e1bdc898d9a96', 63, 'bootstrap', 'verified', '2026-08-10 00:00:00+00'::timestamptz, 'ac05f4c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | S0 §K JSON recorded "dc6e1bdc898d9a967a" (18 hex chars, 2 extra) instead of the 16-char manifest format -- a transcription artifact. The first 16 characters match exactly; recomputed first-party via sha256 of the exact currently-committed file to confirm. | manifest recorded applied_by as "(local, not yet committed)" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-10_mesa_decouple_payment_from_close.sql', '647e731a3bd607f3', 64, 'bootstrap', 'verified', '2026-08-10 00:00:00+00'::timestamptz, 'ac05f4c', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "(local, this session)" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-10_service_lifecycle_economic_boundary_v1.sql', 'f76543f7f1054ccc', 65, 'bootstrap', 'verified', '2026-08-10 00:00:00+00'::timestamptz, '444442e', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "applied" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-11_service_lifecycle_economic_boundary_v1_audit_fix.sql', 'c175f8d19c191a7c', 66, 'bootstrap', 'verified', '2026-08-11 00:00:00+00'::timestamptz, 'a355869', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "applied" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-12_service_session_close_stale_return_fix.sql', '1ede59519bf77160', 67, 'bootstrap', 'verified', '2026-08-12 00:00:00+00'::timestamptz, '4a439b5', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-13_guard_service_session_closed_incident_safe_exemption.sql', '8789a5623bd98a14', 68, 'bootstrap', 'verified', '2026-08-13 00:00:00+00'::timestamptz, 'b4ce434', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "(local, not yet committed)" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-14_mesa_covers_authoritative_on_selection.sql', '27bdc06d366b73db', 69, 'bootstrap', 'verified', '2026-08-14 00:00:00+00'::timestamptz, '3953535', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "(local, not yet committed)" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-15_begin_service_session_close_incident_safe_exemption.sql', 'c5103d5bfd438ad5', 70, 'bootstrap', 'verified', '2026-08-15 00:00:00+00'::timestamptz, '67d178b', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'present in the Supabase-managed migration ledger by exact slug | manifest recorded applied_by as "183ed7d (allowActiveRiderTripAcrossBoundary, preceding this migration)" (stale placeholder, never retroactively filled in); resolved first-party via git log --diff-filter=A against the actual committed file history. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-15_s1_guard_null_payment_idempotency.sql', 'b56385d2648dd427', 71, 'bootstrap', 'bootstrapped_unverified', '2026-08-15 00:00:00+00'::timestamptz, '35cc137', NULL, NULL, NULL, 'No exact filename-slug match in supabase_migrations.schema_migrations: the live ledger holds ''s1_guard_null_payment_idempotency_v2'' (a ''_v2'' suffix), not the exact slug ''s1_guard_null_payment_idempotency''. Applying S0 §K''s own mechanical method (exact match only, no fuzzy inference) yields bootstrapped_unverified -- never asserted verified on an inexact match, per S4''s own domain rule. | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-15_s1_auth_audit_payment_events.sql', '7d05b06fa3ca2f30', 72, 'bootstrap', 'verified', '2026-08-15 00:00:00+00'::timestamptz, '35cc137', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'Exact filename-slug match confirmed live in supabase_migrations.schema_migrations (''s1_auth_audit_payment_events''). | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.'),
  ('2026-08-15_s2_attribution_writers_receipt_service.sql', 'ad5e45e02c45cdf8', 73, 'bootstrap', 'verified', '2026-08-15 00:00:00+00'::timestamptz, '3279a0e', now(), 'S4_bootstrap_seed', 'manifest filename slug matched against supabase_migrations.schema_migrations.name', 'Exact filename-slug match confirmed live in supabase_migrations.schema_migrations (''s2_attribution_writers_receipt_service''). | applied_at is day-level precision, sourced from the manifest''s recorded date, not a captured original timestamp.')
ON CONFLICT (filename) DO NOTHING;

-- ── Post-condition assertions ───────────────────────────────────────────
DO $$
DECLARE
  v_total      integer;
  v_verified   integer;
  v_unverified integer;
  v_max_order  integer;
BEGIN
  SELECT count(*) INTO v_total FROM public.ladieci_schema_migrations WHERE kind = 'bootstrap';
  SELECT count(*) INTO v_verified FROM public.ladieci_schema_migrations WHERE kind = 'bootstrap' AND verification_status = 'verified';
  SELECT count(*) INTO v_unverified FROM public.ladieci_schema_migrations WHERE kind = 'bootstrap' AND verification_status = 'bootstrapped_unverified';
  SELECT max(apply_order) INTO v_max_order FROM public.ladieci_schema_migrations;

  IF v_total <> 73 THEN
    RAISE EXCEPTION 'S4 bootstrap-seed post-condition failed: expected 73 bootstrap rows, found %', v_total;
  END IF;
  IF v_verified <> 38 THEN
    RAISE EXCEPTION 'S4 bootstrap-seed post-condition failed: expected 38 verified rows, found %', v_verified;
  END IF;
  IF v_unverified <> 35 THEN
    RAISE EXCEPTION 'S4 bootstrap-seed post-condition failed: expected 35 bootstrapped_unverified rows, found %', v_unverified;
  END IF;
  IF v_max_order <> 73 THEN
    RAISE EXCEPTION 'S4 bootstrap-seed post-condition failed: expected max(apply_order) = 73, found %', v_max_order;
  END IF;
END $$;
