#!/usr/bin/env node
'use strict';
// V3 GREENFIELD BASELINE (tip 138) -- catalog sanitizer, generator, catalog extractor, fingerprint and comparator.
//
// WHY. The pre-139 migration history cannot build an empty database: 86 of its files assert on rows only the staging database ever had
// (seeded sessions, captured live bodies, one-off data repairs), 4 function bodies exist only in staging and 6 are staging variants. A
// production V3 database must not depend on staging existing first. The greenfield baseline is ONE deterministic structural file that brings
// an empty Supabase PostgreSQL 17 database to exactly the structural state the Economy package (139 -> 156) is certified against: schemas,
// sequences, tables, functions (byte-exact bodies, so every md5 pin of 139..156 holds), defaults, constraints, indexes, triggers (including
// the application trigger on the platform table auth.users), RLS + policies, privileges, comments, the realtime publication membership and
// the three system singletons (service_session_state, business_day_policy, business_day_lifecycle_state) with their column defaults, and the
// dispatch lock anchor config('DRIVER_STATO', '{}') with the value the code itself creates lazily (see section 15 of the generated file).
//
// It carries NO business data and NO staging value: no workspace, no actor, no user, no order, no table, no menu, no business config, no UUID,
// no pointer value, no migration-ledger row. The ledger row that stands for the baseline and the Supabase registry row are written by the
// installer (scripts/economyChainApply.js) after the file is applied, exactly as for every later migration. Workspace, owner, the four
// canonical actors, tables, menu and restaurant configuration are the BUSINESS BOOTSTRAP (scripts/v3BusinessBootstrap.js,
// docs/V3_GREENFIELD_INSTALL_AND_BOOTSTRAP_CONTRACT.md), never part of the schema baseline.
//
// Layers (kept separate on purpose):
//   PLATFORM_PREREQUISITES   what Supabase provides (roles, extensions.pgcrypto, auth.users, supabase_realtime, supabase_migrations, the
//                            default privileges of schema public). Checked by the baseline's guard, never created by it. Lab stand-in:
//                            ci/greenfield/supabase_platform_emulation.lab.sql (NEVER on a Supabase project).
//   LA_DIECI_V3_SCHEMA       migrations/baseline/2026-09-27_v3_greenfield_baseline_tip138.sql, generated by this script from the
//                            committed structural catalog migrations/baseline/catalog_tip138/ (functions.json, structure.json, extras.json).
//
// Source of truth for the STRUCTURE: the read-only catalog of the staging database at ledger tip 138 (2026-09-27), sanitized by
// `catalog-from-snapshot` (structure only: the staging ledger / registry / row counts / platform default ACLs are dropped).
// The same extraction queries (`sql` / `extract`) run against any database give a comparable catalog.
//
// Usage:
//   node scripts/v3GreenfieldBaseline.js sql functions|structure|extras              print one extraction query (read-only)
//   node scripts/v3GreenfieldBaseline.js extract <catalogDir>                         run them on PREFLIGHT_DATABASE_URL / PG* env (READ ONLY)
//   node scripts/v3GreenfieldBaseline.js catalog-from-snapshot <snapshotDir> <outDir> sanitize a raw staging snapshot into a repo catalog
//   node scripts/v3GreenfieldBaseline.js generate <catalogDir> <out.sql>              write the baseline SQL from a catalog
//   node scripts/v3GreenfieldBaseline.js verify [<catalogDir> <baseline.sql>]         regenerate and byte-compare (default: the committed pair)
//   node scripts/v3GreenfieldBaseline.js fingerprint <catalogDir>                     normalized structural fingerprint (sha256 per section)
//   node scripts/v3GreenfieldBaseline.js compare <catalogDirA> <catalogDirB>          every structural difference (exit 1 if any)

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const CATALOG_DIR = path.join(ROOT, 'migrations/baseline/catalog_tip138');
const BASELINE_FILE = 'migrations/baseline/2026-09-27_v3_greenfield_baseline_tip138.sql';
const SCHEMAS = ['public', 'giro_authority', 'trip_authority'];
const IN_SCHEMAS = `(${SCHEMAS.map((s) => `'${s}'`).join(',')})`;
const sha256 = (s) => crypto.createHash('sha256').update(s).digest('hex');
// Canonical JSON (object keys sorted): the fingerprint and the comparison never depend on key order.
const canon = (v) => (Array.isArray(v) ? `[${v.map(canon).join(',')}]` : v && typeof v === 'object' ? `{${Object.keys(v).sort().map((k) => `${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}` : JSON.stringify(v === undefined ? null : v));

// The extraction runs with the staging session search_path, so every deparsed expression is qualified the same way on both sides.
const EXTRACT_SEARCH_PATH = 'SET search_path = "$user", public, extensions';
const SQL = {
  functions: `SELECT json_agg(json_build_object('schema', n.nspname, 'name', p.proname, 'identity_args', pg_get_function_identity_arguments(p.oid), 'kind', p.prokind,
  'md5_prosrc', md5(p.prosrc), 'secdef', p.prosecdef, 'volatility', p.provolatile, 'config', p.proconfig, 'owner', pg_get_userbyid(p.proowner), 'acl', p.proacl::text[],
  'lang', l.lanname, 'def', CASE WHEN p.prokind = 'a' THEN NULL ELSE pg_get_functiondef(p.oid) END) ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) AS functions
FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace JOIN pg_language l ON l.oid = p.prolang
WHERE n.nspname IN ${IN_SCHEMAS}`,
  structure: `WITH sch AS (SELECT oid, nspname FROM pg_namespace WHERE nspname IN ${IN_SCHEMAS})
SELECT json_build_object(
 'schemas', (SELECT json_agg(json_build_object('name', nspname, 'owner', pg_get_userbyid(n.nspowner), 'acl', n.nspacl::text[]) ORDER BY nspname) FROM pg_namespace n WHERE n.oid IN (SELECT oid FROM sch)),
 'tables', (SELECT json_agg(json_build_object('schema', s.nspname, 'name', c.relname, 'kind', c.relkind, 'rls', c.relrowsecurity, 'force_rls', c.relforcerowsecurity, 'owner', pg_get_userbyid(c.relowner), 'acl', c.relacl::text[],
     'comment', obj_description(c.oid, 'pg_class'), 'replident', c.relreplident, 'persistence', c.relpersistence, 'reloptions', c.reloptions,
     'columns', (SELECT json_agg(json_build_object('n', a.attnum, 'name', a.attname, 'type', format_type(a.atttypid, a.atttypmod), 'notnull', a.attnotnull, 'default', pg_get_expr(d.adbin, d.adrelid), 'identity', a.attidentity, 'generated', a.attgenerated, 'acl', a.attacl::text[], 'comment', col_description(c.oid, a.attnum)) ORDER BY a.attnum)
                 FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped),
     'constraints', (SELECT json_agg(json_build_object('name', co.conname, 'type', co.contype, 'def', pg_get_constraintdef(co.oid), 'deferrable', co.condeferrable, 'deferred', co.condeferred, 'comment', obj_description(co.oid, 'pg_constraint')) ORDER BY co.conname) FROM pg_constraint co WHERE co.conrelid = c.oid),
     'indexes', (SELECT json_agg(json_build_object('name', ic.relname, 'def', pg_get_indexdef(i.indexrelid)) ORDER BY ic.relname) FROM pg_index i JOIN pg_class ic ON ic.oid = i.indexrelid WHERE i.indrelid = c.oid),
     'triggers', (SELECT json_agg(json_build_object('name', t.tgname, 'def', pg_get_triggerdef(t.oid), 'enabled', t.tgenabled) ORDER BY t.tgname) FROM pg_trigger t WHERE t.tgrelid = c.oid AND NOT t.tgisinternal),
     'policies', (SELECT json_agg(json_build_object('name', po.polname, 'cmd', po.polcmd, 'permissive', po.polpermissive, 'roles', (SELECT json_agg(r ORDER BY r) FROM (SELECT CASE WHEN x = 0 THEN 'public' ELSE pg_get_userbyid(x) END r FROM unnest(po.polroles) x) y), 'qual', pg_get_expr(po.polqual, po.polrelid), 'check', pg_get_expr(po.polwithcheck, po.polrelid)) ORDER BY po.polname) FROM pg_policy po WHERE po.polrelid = c.oid)
   ) ORDER BY s.nspname, c.relname) FROM pg_class c JOIN sch s ON s.oid = c.relnamespace WHERE c.relkind IN ('r','p','v','m')),
 'sequences', (SELECT json_agg(json_build_object('schema', s.nspname, 'name', c.relname, 'type', format_type(q.seqtypid, NULL), 'start', q.seqstart, 'increment', q.seqincrement, 'min', q.seqmin, 'max', q.seqmax, 'cache', q.seqcache, 'cycle', q.seqcycle, 'acl', c.relacl::text[],
     'owned_by', (SELECT dc.relname || '.' || da.attname FROM pg_depend dp JOIN pg_class dc ON dc.oid = dp.refobjid JOIN pg_attribute da ON da.attrelid = dp.refobjid AND da.attnum = dp.refobjsubid WHERE dp.objid = c.oid AND dp.deptype IN ('a','i') LIMIT 1)) ORDER BY s.nspname, c.relname)
   FROM pg_class c JOIN sch s ON s.oid = c.relnamespace JOIN pg_sequence q ON q.seqrelid = c.oid),
 'publications', (SELECT json_agg(json_build_object('pub', pubname, 'schema', schemaname, 'table', tablename) ORDER BY pubname, schemaname, tablename) FROM pg_publication_tables WHERE schemaname IN ${IN_SCHEMAS})
) AS catalog`,
  extras: `SELECT json_build_object(
 'function_comments', (SELECT json_agg(json_build_object('schema', n.nspname, 'name', p.proname, 'args', pg_get_function_identity_arguments(p.oid), 'comment', d.description) ORDER BY n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace JOIN pg_description d ON d.objoid = p.oid AND d.classoid = 'pg_proc'::regclass WHERE n.nspname IN ${IN_SCHEMAS}),
 'schema_comments', (SELECT json_agg(json_build_object('schema', n.nspname, 'comment', obj_description(n.oid, 'pg_namespace')) ORDER BY n.nspname) FROM pg_namespace n WHERE n.nspname IN ${IN_SCHEMAS} AND n.nspname <> 'public' AND obj_description(n.oid, 'pg_namespace') IS NOT NULL),
 'platform_triggers', (SELECT json_agg(json_build_object('table', tn.nspname || '.' || c.relname, 'name', t.tgname, 'def', pg_get_triggerdef(t.oid), 'enabled', t.tgenabled) ORDER BY tn.nspname, c.relname, t.tgname) FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid JOIN pg_namespace tn ON tn.oid = c.relnamespace JOIN pg_proc p ON p.oid = t.tgfoid JOIN pg_namespace pn ON pn.oid = p.pronamespace WHERE NOT t.tgisinternal AND pn.nspname IN ${IN_SCHEMAS} AND tn.nspname NOT IN ${IN_SCHEMAS})
) AS extras`,
  // Row-level facts of the structural singletons (checked, never fingerprinted as structure).
  system_rows: `SELECT json_build_object(
 'service_session_state', (SELECT json_agg(json_build_object('singleton', singleton, 'current_session_id', current_session_id, 'recent_closed_session_id', recent_closed_session_id)) FROM public.service_session_state),
 'business_day_policy', (SELECT json_agg(json_build_object('singleton', singleton, 'auto_seal_local_time', auto_seal_local_time, 'seal_timezone', seal_timezone, 'ticket_reset_on_consolidation_default', ticket_reset_on_consolidation_default)) FROM public.business_day_policy),
 'business_day_lifecycle_state', (SELECT json_agg(json_build_object('singleton', singleton, 'current_business_day_id', current_business_day_id, 'current_period_id', current_period_id, 'current_ticket_epoch', current_ticket_epoch, 'recent_closed_business_day_id', recent_closed_business_day_id)) FROM public.business_day_lifecycle_state),
 'config', (SELECT json_agg(json_build_object('chiave', chiave, 'valore', valore) ORDER BY chiave) FROM public.config)
) AS system_rows`,
};

// ── helpers ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
const qi = (s) => (/^[a-z_][a-z0-9_]*$/.test(s) ? s : `"${s.replace(/"/g, '""')}"`);
const qn = (schema, name) => `${qi(schema)}.${qi(name)}`;
const lit = (s) => (s === null || s === undefined ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);
const API_ROLES = ['anon', 'authenticated', 'service_role'];
const TABLE_PRIVS = { r: 'SELECT', a: 'INSERT', w: 'UPDATE', d: 'DELETE', D: 'TRUNCATE', x: 'REFERENCES', t: 'TRIGGER', m: 'MAINTAIN' };
const SEQ_PRIVS = { r: 'SELECT', w: 'UPDATE', U: 'USAGE' };
const SCHEMA_PRIVS = { U: 'USAGE', C: 'CREATE' };
const COL_PRIVS = { r: 'SELECT', a: 'INSERT', w: 'UPDATE', x: 'REFERENCES' };
// JSON numbers lose the int8 bounds (9223372036854775807 -> 9223372036854776000): restore the exact PostgreSQL value.
const INT8_MAX = '9223372036854775807'; const INT8_MIN = '-9223372036854775808';
const seqBound = (v) => (Number(v) >= 9.2e18 ? INT8_MAX : Number(v) <= -9.2e18 ? INT8_MIN : String(v));
// parse "grantee=privs/grantor" -> {grantee, privs: [{p, grant}]}
function parseAcl(item) {
  const m = /^([^=]*)=([^/]*)\/(.*)$/.exec(item);
  if (!m) throw new Error('unparsable aclitem ' + item);
  const grantee = m[1] === '' ? 'PUBLIC' : m[1].replace(/^"|"$/g, '');
  const privs = []; const s = m[2];
  for (let i = 0; i < s.length; i += 1) { const grant = s[i + 1] === '*'; privs.push({ p: s[i], grant }); if (grant) i += 1; }
  return { grantee, privs, grantor: m[3] };
}
function grantsSql(kind, objSql, acl, owner, map) {
  // Start from a clean slate for every role the platform's default privileges may have touched, then grant exactly the catalog ACL.
  const out = [`REVOKE ALL ON ${kind} ${objSql} FROM PUBLIC, ${API_ROLES.join(', ')};`];
  for (const it of acl || []) {
    const a = parseAcl(it);
    if (a.grantee === owner) continue;
    const plain = a.privs.filter((x) => !x.grant).map((x) => map[x.p]);
    const withGrant = a.privs.filter((x) => x.grant).map((x) => map[x.p]);
    const role = a.grantee === 'PUBLIC' ? 'PUBLIC' : qi(a.grantee);
    if (plain.length) out.push(`GRANT ${plain.join(', ')} ON ${kind} ${objSql} TO ${role};`);
    if (withGrant.length) out.push(`GRANT ${withGrant.join(', ')} ON ${kind} ${objSql} TO ${role} WITH GRANT OPTION;`);
  }
  return out;
}
const readJson = (dir, f) => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
const load = (dir) => ({ functions: readJson(dir, 'functions.json'), structure: readJson(dir, 'structure.json'), extras: readJson(dir, 'extras.json') });
const stable = (v) => JSON.stringify(v, null, 1) + '\n';

// ── sanitizer: raw staging snapshot -> committed structural catalog ────────────────────────────────────────────────────────────────
// Keeps structure only. Dropped: ledger, registry, row_counts_structural (staging rows), default_acl (platform), cron_jobs / types (null),
// publication rows outside the application schemas (platform realtime.messages_* partitions). Per-table attributes measured separately
// (replica identity, persistence, reloptions) are merged from extras2; function / schema comments and the platform trigger from extras.
function catalogFromSnapshot(dir) {
  const functions = readJson(dir, 'functions.json');
  const raw = readJson(dir, 'structure.json');
  const ex = readJson(dir, 'extras_staging_readonly_query_2026-09-27.json').extras;
  const ex2 = readJson(dir, 'extras2_staging_readonly_query_2026-09-27.json');
  if (!/replident":"d for all 62/.test(JSON.stringify(ex2.result_summary)) || ex2.result_summary.tables_checked !== raw.tables.length) throw new Error('extras2 does not cover every table');
  const structure = {
    schemas: raw.schemas,
    tables: raw.tables.map((t) => ({ ...t, replident: 'd', persistence: 'p', reloptions: null })),
    sequences: raw.sequences,
    publications: (raw.publications || []).filter((p) => SCHEMAS.includes(p.schema)),
  };
  const extras = {
    function_comments: ex.function_comments,
    schema_comments: (ex.schema_comments || []).filter((s) => s.schema !== 'public'),
    platform_triggers: ex.app_triggers_on_platform_tables.map((t) => ({ table: t.table, name: t.name, def: t.def, enabled: t.enabled })),
  };
  return { functions, structure, extras };
}

// A CHECK written with BETWEEN is stored as a nested AND ((e >= lo) AND (e <= hi)) that the parser never flattens into the enclosing AND
// list, while re-parsing its deparsed text does flatten it. Writing that exact shape back as BETWEEN restores the original expression tree,
// so pg_get_constraintdef round-trips byte for byte (proved by the catalog comparison, not assumed).
const betweenForm = (def) => def.replace(/\(\(([^()]*(?:\([^()]*\))?[^()]*) >= ([^()\s]+)\) AND \(\1 <= ([^()\s]+)\)\)/g, '($1 BETWEEN $2 AND $3)');

// ── generator ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
function generate(cat) {
  const { functions, structure, extras } = cat;
  const L = [];
  const P = (...x) => L.push(...x);
  const tables = structure.tables.filter((t) => t.kind === 'r' || t.kind === 'p');
  if (tables.length !== structure.tables.length) throw new Error('views / materialized views are not supported by this generator');
  const identitySeq = new Set(structure.sequences.filter((s) => s.owned_by && tables.some((t) => t.schema === s.schema && t.columns.some((c) => c.identity && `${t.name}.${c.name}` === s.owned_by))).map((s) => `${s.schema}.${s.name}`));
  for (const t of tables) if (t.replident !== 'd' || t.persistence !== 'p' || t.reloptions) throw new Error(`non-default table attributes on ${t.name}: extend the generator`);
  P('-- migrations/baseline/2026-09-27_v3_greenfield_baseline_tip138.sql',
    '-- LA_DIECI_V3_SCHEMA -- V3 GREENFIELD BASELINE: the structural state at migration-ledger tip 138.',
    '-- GENERATED by scripts/v3GreenfieldBaseline.js from migrations/baseline/catalog_tip138/ (the sanitized read-only staging catalog). DO NOT EDIT:',
    '-- regenerate, then `node scripts/v3GreenfieldBaseline.js verify`. Structure only: no business row, no staging value, no ledger row.',
    '-- Apply ONCE, through scripts/economyChainApply.js (it applies this file, then writes its ledger row and its Supabase registry row, then',
    '-- runs the Economy chain 139 -> 156), as role postgres, on an EMPTY Supabase PostgreSQL 17 database, with client_encoding UTF8 (several',
    '-- function bodies carry non-ASCII text and are byte-exact). The guard below refuses any database that is not greenfield or that lacks a',
    '-- PLATFORM_PREREQUISITE (docs/V3_GREENFIELD_INSTALL_AND_BOOTSTRAP_CONTRACT.md).',
    'BEGIN;',
    "SET LOCAL client_encoding = 'UTF8';",
    'SET LOCAL check_function_bodies = off;',
    // pg_catalog stays implicitly FIRST (as in the staging session that deparsed the catalog): gen_random_uuid() must resolve to the core
    // function, not to the pgcrypto copy in schema extensions.
    'SET LOCAL search_path = public, extensions;',
    `DO $guard$ BEGIN
  IF current_setting('server_version_num')::int NOT BETWEEN 170000 AND 179999 THEN RAISE EXCEPTION 'V3_BASELINE refused: PostgreSQL 17 required'; END IF;
  IF current_setting('server_encoding') <> 'UTF8' THEN RAISE EXCEPTION 'V3_BASELINE refused: server_encoding UTF8 required'; END IF;
  IF current_user <> 'postgres' THEN RAISE EXCEPTION 'V3_BASELINE refused: apply as role postgres (object owner), not %', current_user; END IF;
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname IN ('giro_authority', 'trip_authority'))
     OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'public')
     OR EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public') THEN
    RAISE EXCEPTION 'V3_BASELINE refused: schema public is not empty or V3 schemas exist (greenfield only)';
  END IF;
  -- PLATFORM_PREREQUISITES (provided by Supabase; never created here)
  IF NOT EXISTS (SELECT 1 FROM pg_extension e JOIN pg_namespace n ON n.oid = e.extnamespace WHERE e.extname = 'pgcrypto' AND n.nspname = 'extensions') THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE extensions.pgcrypto missing'; END IF;
  IF (SELECT count(*) FROM pg_roles WHERE rolname IN ('anon', 'authenticated', 'service_role')) <> 3 THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE API roles missing'; END IF;
  IF NOT (SELECT rolbypassrls FROM pg_roles WHERE rolname = 'service_role') THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE service_role must be BYPASSRLS'; END IF;
  IF to_regclass('auth.users') IS NULL OR to_regprocedure('auth.uid()') IS NULL THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE auth.users / auth.uid() missing'; END IF;
  IF NOT has_table_privilege('auth.users', 'REFERENCES') OR NOT has_table_privilege('auth.users', 'TRIGGER') THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE postgres needs REFERENCES + TRIGGER on auth.users'; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN RAISE EXCEPTION 'V3_BASELINE refused: PLATFORM_PREREQUISITE publication supabase_realtime missing'; END IF;
END $guard$;`);
  // 1. schemas (public belongs to the platform)
  P('', '-- 1. schemas');
  for (const s of structure.schemas) if (s.name !== 'public') P(`CREATE SCHEMA ${qi(s.name)};`);
  // 2. standalone sequences (identity sequences are created by their column)
  P('', '-- 2. standalone sequences');
  for (const s of structure.sequences) {
    if (identitySeq.has(`${s.schema}.${s.name}`)) continue;
    P(`CREATE SEQUENCE ${qn(s.schema, s.name)} AS ${s.type} INCREMENT BY ${s.increment} MINVALUE ${seqBound(s.min)} MAXVALUE ${seqBound(s.max)} START WITH ${s.start} CACHE ${s.cache}${s.cycle ? ' CYCLE' : ' NO CYCLE'};`);
  }
  // 3. tables (columns, NOT NULL, identity) -- defaults come after the functions
  P('', '-- 3. tables');
  for (const t of tables) {
    const cols = t.columns.map((c) => {
      if (c.generated) throw new Error(`generated column ${t.name}.${c.name}: extend the generator`);
      let s = `  ${qi(c.name)} ${c.type}`;
      if (c.identity) {
        const seq = structure.sequences.find((q) => q.owned_by === `${t.name}.${c.name}` && q.schema === t.schema);
        if (!seq) throw new Error(`identity column ${t.name}.${c.name} without its sequence in the catalog`);
        s += ` GENERATED ${c.identity === 'a' ? 'ALWAYS' : 'BY DEFAULT'} AS IDENTITY (SEQUENCE NAME ${qn(seq.schema, seq.name)} INCREMENT BY ${seq.increment} MINVALUE ${seqBound(seq.min)} MAXVALUE ${seqBound(seq.max)} START WITH ${seq.start} CACHE ${seq.cache}${seq.cycle ? ' CYCLE' : ' NO CYCLE'})`;
      }
      if (c.notnull) s += ' NOT NULL';
      return s;
    });
    P(`CREATE TABLE ${qn(t.schema, t.name)} (\n${cols.join(',\n')}\n);`);
  }
  // 4. functions, byte-exact
  P('', '-- 4. functions (pg_get_functiondef of the source catalog; bodies byte-exact)');
  for (const f of functions) {
    if (f.kind !== 'f') throw new Error(`routine kind ${f.kind} (${f.name}): extend the generator`);
    P(f.def.replace(/\s+$/, '') + ';', '');
  }
  // 5. defaults
  P('-- 5. column defaults');
  for (const t of tables) for (const c of t.columns) if (c.default !== null && !c.identity) P(`ALTER TABLE ${qn(t.schema, t.name)} ALTER COLUMN ${qi(c.name)} SET DEFAULT ${c.default};`);
  // 6. constraints: primary / unique / exclusion / check first, foreign keys last (constraint triggers are created with the triggers).
  //    pg_get_constraintdef already carries DEFERRABLE / INITIALLY DEFERRED / NOT VALID.
  const cons = (types) => { for (const t of tables) for (const k of t.constraints || []) if (types.includes(k.type)) P(`ALTER TABLE ${qn(t.schema, t.name)} ADD CONSTRAINT ${qi(k.name)} ${k.type === 'c' ? betweenForm(k.def) : k.def};`); };
  P('', '-- 6. constraints'); cons(['p', 'u', 'x', 'c']);
  // 7. indexes that do not back a constraint
  P('', '-- 7. indexes');
  for (const t of tables) {
    const backing = new Set((t.constraints || []).filter((k) => ['p', 'u', 'x'].includes(k.type)).map((k) => k.name));
    for (const i of t.indexes || []) if (!backing.has(i.name)) P(`${i.def};`);
  }
  P('', '-- 8. foreign keys'); cons(['f']);
  for (const t of tables) for (const k of t.constraints || []) if (!['p', 'u', 'x', 'c', 'f', 't'].includes(k.type)) throw new Error(`constraint type ${k.type} (${k.name}): extend the generator`);
  // 9. sequence ownership (serial-style, non-identity)
  P('', '-- 9. sequence ownership');
  for (const s of structure.sequences) if (s.owned_by && !identitySeq.has(`${s.schema}.${s.name}`)) { const [tb, col] = s.owned_by.split('.'); P(`ALTER SEQUENCE ${qn(s.schema, s.name)} OWNED BY ${qn(s.schema, tb)}.${qi(col)};`); }
  // 10. triggers (application tables, then the application trigger on the platform table auth.users)
  P('', '-- 10. triggers');
  const ENABLE = { D: 'DISABLE TRIGGER', R: 'ENABLE REPLICA TRIGGER', A: 'ENABLE ALWAYS TRIGGER' };
  for (const t of tables) for (const g of t.triggers || []) { P(`${g.def};`); if (g.enabled !== 'O') P(`ALTER TABLE ${qn(t.schema, t.name)} ${ENABLE[g.enabled]} ${qi(g.name)};`); }
  for (const g of extras.platform_triggers || []) { if (g.enabled !== 'O') throw new Error('platform trigger not enabled-origin'); P(`${g.def};`); }
  // 11. RLS + policies
  P('', '-- 11. row level security');
  const CMD = { r: 'SELECT', a: 'INSERT', w: 'UPDATE', d: 'DELETE', '*': 'ALL' };
  for (const t of tables) {
    if (t.rls) P(`ALTER TABLE ${qn(t.schema, t.name)} ENABLE ROW LEVEL SECURITY;`);
    if (t.force_rls) P(`ALTER TABLE ${qn(t.schema, t.name)} FORCE ROW LEVEL SECURITY;`);
    for (const p of t.policies || []) P(`CREATE POLICY ${qi(p.name)} ON ${qn(t.schema, t.name)} AS ${p.permissive ? 'PERMISSIVE' : 'RESTRICTIVE'} FOR ${CMD[p.cmd]} TO ${p.roles.map((r) => (r === 'public' ? 'public' : qi(r))).join(', ')}${p.qual ? ` USING (${p.qual})` : ''}${p.check ? ` WITH CHECK (${p.check})` : ''};`);
  }
  // 12. privileges: exact catalog ACLs (the platform default privileges of schema public are revoked first). Schema public: platform.
  P('', '-- 12. privileges (exact catalog ACLs; platform default privileges are revoked first; schema public is left to the platform)');
  for (const s of structure.schemas) if (s.name !== 'public') for (const g of grantsSql('SCHEMA', qi(s.name), s.acl, s.owner, SCHEMA_PRIVS)) P(g);
  for (const s of structure.sequences) for (const g of grantsSql('SEQUENCE', qn(s.schema, s.name), s.acl, 'postgres', SEQ_PRIVS)) P(g);
  for (const t of tables) {
    for (const g of grantsSql('TABLE', qn(t.schema, t.name), t.acl, t.owner, TABLE_PRIVS)) P(g);
    for (const c of t.columns) for (const it of c.acl || []) {
      const a = parseAcl(it); if (a.grantee === t.owner) continue;
      P(`GRANT ${a.privs.map((x) => COL_PRIVS[x.p]).join(', ')} (${qi(c.name)}) ON TABLE ${qn(t.schema, t.name)} TO ${a.grantee === 'PUBLIC' ? 'PUBLIC' : qi(a.grantee)};`);
    }
  }
  for (const f of functions) {
    if (f.acl === null || f.acl === undefined) throw new Error(`function ${f.name} has a NULL ACL in the catalog: state it explicitly`);
    for (const g of grantsSql('FUNCTION', `${qn(f.schema, f.name)}(${f.identity_args})`, f.acl, f.owner, { X: 'EXECUTE' })) P(g);
  }
  // 13. comments
  P('', '-- 13. comments');
  for (const s of extras.schema_comments || []) P(`COMMENT ON SCHEMA ${qi(s.schema)} IS ${lit(s.comment)};`);
  for (const t of tables) {
    if (t.comment) P(`COMMENT ON TABLE ${qn(t.schema, t.name)} IS ${lit(t.comment)};`);
    for (const c of t.columns) if (c.comment) P(`COMMENT ON COLUMN ${qn(t.schema, t.name)}.${qi(c.name)} IS ${lit(c.comment)};`);
    for (const k of t.constraints || []) if (k.comment) P(`COMMENT ON CONSTRAINT ${qi(k.name)} ON ${qn(t.schema, t.name)} IS ${lit(k.comment)};`);
  }
  for (const c of extras.function_comments || []) P(`COMMENT ON FUNCTION ${qn(c.schema, c.name)}(${c.args}) IS ${lit(c.comment)};`);
  // 14. realtime publication membership (the platform publication must exist: checked by the guard)
  P('', '-- 14. realtime publication membership');
  for (const p of structure.publications || []) P(`ALTER PUBLICATION ${qi(p.pub)} ADD TABLE ${qn(p.schema, p.table)};`);
  // 15. system singletons: one row each, every value from the column defaults (pointers NULL). No workspace, actor or business row.
  P('', '-- 15. structural singletons (column defaults only; no business data)',
    'INSERT INTO public.service_session_state (singleton) VALUES (true);',
    'INSERT INTO public.business_day_policy (singleton) VALUES (true);',
    'INSERT INTO public.business_day_lifecycle_state (singleton) VALUES (true);',
    '-- The dispatch lock anchor. delete_order_if_not_active, delete_conversation_if_not_active, close_rider_trip and rider_collect_and_complete_stop',
    "-- serialise on SELECT ... FROM public.config WHERE chiave = 'DRIVER_STATO' FOR UPDATE and never create the row; only start_rider_trip_v2 and",
    "-- the legacy close functions create it lazily, with exactly the value '{}'. Without it a greenfield database would take NO lock there until",
    "-- the first trip ever. It is seeded with the code's own initial value (not a staging value); it carries no business configuration.",
    "INSERT INTO public.config (chiave, valore) VALUES ('DRIVER_STATO', '{}');");
  // 16. post-conditions: every function body is the catalog body (md5 of prosrc), every table exists
  P('', '-- 16. post-conditions',
    `DO $post$ DECLARE v_bad text; BEGIN
  SELECT string_agg(x.nsp || '.' || x.fn || '(' || x.args || ')', ', ') INTO v_bad FROM (VALUES
${functions.map((f) => `    (${lit(f.schema)}, ${lit(f.name)}, ${lit(f.identity_args)}, ${lit(f.md5_prosrc)})`).join(',\n')}
  ) AS x(nsp, fn, args, want)
  WHERE (SELECT md5(p.prosrc) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
          WHERE n.nspname = x.nsp AND p.proname = x.fn AND pg_get_function_identity_arguments(p.oid) = x.args) IS DISTINCT FROM x.want;
  IF v_bad IS NOT NULL THEN RAISE EXCEPTION 'V3_BASELINE post-condition: function body differs from the catalog: %', v_bad; END IF;
  IF (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname IN ${IN_SCHEMAS}) <> ${functions.length} THEN RAISE EXCEPTION 'V3_BASELINE post-condition: function count'; END IF;
  IF (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname IN ${IN_SCHEMAS} AND c.relkind = 'r') <> ${tables.length} THEN RAISE EXCEPTION 'V3_BASELINE post-condition: table count'; END IF;
END $post$;`);
  P('', 'COMMIT;', '');
  return L.join('\n');
}

// ── normalized fingerprint (owners, grantors, platform rows and row data excluded) ────────────────────────────────────────────────
function normalize(cat) {
  const { functions, structure, extras } = cat;
  const acl = (a, owner) => (a === null || a === undefined ? null : a.map(parseAcl).filter((x) => x.grantee !== owner).map((x) => `${x.grantee}=${x.privs.map((p) => p.p + (p.grant ? '*' : '')).join('')}`).sort());
  const fnAcl = (a, owner) => (a === null || a === undefined ? ['PUBLIC=X'] : acl(a, owner));
  const num = (v) => seqBound(v);
  return {
    schemas: structure.schemas.map((s) => ({ name: s.name, acl: acl(s.acl, s.owner) })),
    sequences: structure.sequences.map((s) => ({ schema: s.schema, name: s.name, type: s.type, start: num(s.start), increment: num(s.increment), min: num(s.min), max: num(s.max), cache: num(s.cache), cycle: s.cycle, owned_by: s.owned_by, acl: acl(s.acl, 'postgres') })),
    tables: structure.tables.map((t) => ({ schema: t.schema, name: t.name, kind: t.kind, rls: t.rls, force_rls: t.force_rls, acl: acl(t.acl, t.owner) || [], comment: t.comment,
      replident: t.replident, persistence: t.persistence, reloptions: t.reloptions || null,
      // attnum is physical: a column dropped on the source leaves a gap there and none on a fresh install. The LOGICAL order (rank) is compared.
      columns: t.columns.map((c, i) => ({ ...c, n: i + 1, acl: acl(c.acl, t.owner) })), constraints: t.constraints || [], indexes: t.indexes || [], triggers: t.triggers || [], policies: t.policies || [] })),
    functions: functions.map((f) => ({ schema: f.schema, name: f.name, args: f.identity_args, kind: f.kind, md5_prosrc: f.md5_prosrc, secdef: f.secdef, volatility: f.volatility,
      config: f.config, lang: f.lang, acl: fnAcl(f.acl, f.owner), def_sha256: sha256(f.def || '') })),
    publications: (structure.publications || []).filter((p) => SCHEMAS.includes(p.schema)),
    function_comments: extras.function_comments || [],
    schema_comments: (extras.schema_comments || []).filter((s) => s.schema !== 'public'),
    platform_triggers: extras.platform_triggers || [],
  };
}
function fingerprint(cat) { const n = normalize(cat); return { sha256: sha256(canon(n)), sections: Object.fromEntries(Object.entries(n).map(([k, v]) => [k, sha256(canon(v))])) }; }
function compare(a, b) {
  const A = normalize(a); const B = normalize(b); const diffs = [];
  const byKey = (list, key) => new Map(list.map((x) => [key(x), x]));
  const cmpList = (section, key) => {
    const ma = byKey(A[section], key); const mb = byKey(B[section], key);
    for (const k of new Set([...ma.keys(), ...mb.keys()])) {
      if (!ma.has(k)) diffs.push({ section, key: k, only: 'B' });
      else if (!mb.has(k)) diffs.push({ section, key: k, only: 'A' });
      else if (canon(ma.get(k)) !== canon(mb.get(k))) {
        const x = ma.get(k); const y = mb.get(k); const fields = Object.keys({ ...x, ...y }).filter((f) => canon(x[f]) !== canon(y[f]));
        const detail = {};
        for (const f of fields) {
          if (Array.isArray(x[f]) && Array.isArray(y[f]) && (x[f].length || y[f].length) && typeof (x[f][0] || y[f][0]) === 'object') {
            const kk = (e) => e.name || canon(e); const xa = byKey(x[f], kk); const ya = byKey(y[f], kk);
            detail[f] = [...new Set([...xa.keys(), ...ya.keys()])].filter((z) => canon(xa.get(z)) !== canon(ya.get(z))).map((z) => ({ item: z, A: xa.get(z) || null, B: ya.get(z) || null }));
          } else detail[f] = { A: x[f], B: y[f] };
        }
        diffs.push({ section, key: k, detail });
      }
    }
  };
  cmpList('schemas', (x) => x.name); cmpList('sequences', (x) => `${x.schema}.${x.name}`); cmpList('tables', (x) => `${x.schema}.${x.name}`);
  cmpList('functions', (x) => `${x.schema}.${x.name}(${x.args})`); cmpList('publications', (x) => `${x.pub}:${x.schema}.${x.table}`);
  cmpList('function_comments', (x) => `${x.schema}.${x.name}(${x.args})`); cmpList('schema_comments', (x) => x.schema);
  cmpList('platform_triggers', (x) => `${x.table}.${x.name}`);
  return diffs;
}

async function withClient(fn) {
  const base = process.env.W3_PG_NODE_MODULES;
  const pg = base ? require(path.join(base, 'pg')) : require('pg');
  const client = process.env.PREFLIGHT_DATABASE_URL ? new pg.Client({ connectionString: process.env.PREFLIGHT_DATABASE_URL }) : new pg.Client();
  await client.connect();
  try { return await fn(client); } finally { await client.end(); }
}
async function extract(dir, client) {
  const run = async (c) => {
    await c.query('BEGIN TRANSACTION READ ONLY');
    try {
      await c.query(EXTRACT_SEARCH_PATH);
      fs.mkdirSync(dir, { recursive: true });
      for (const [k, q, col] of [['functions', SQL.functions, 'functions'], ['structure', SQL.structure, 'catalog'], ['extras', SQL.extras, 'extras']]) {
        const r = await c.query(q); fs.writeFileSync(path.join(dir, `${k}.json`), stable(r.rows[0][col]));
      }
    } finally { await c.query('ROLLBACK'); }
  };
  return client ? run(client) : withClient(run);
}
async function systemRows(client) {
  await client.query('BEGIN TRANSACTION READ ONLY');
  try { return (await client.query(SQL.system_rows)).rows[0].system_rows; } finally { await client.query('ROLLBACK'); }
}
// The structural rows of a freshly installed database: exactly one row per singleton, pointers NULL, policy at its column defaults, and the
// config table holding only the DRIVER_STATO lock anchor with the code's initial value. (After the business bootstrap, config gains rows.)
function systemRowsProblems(rows) {
  const out = [];
  const one = (k) => (Array.isArray(rows[k]) && rows[k].length === 1 ? rows[k][0] : (out.push(`${k}: expected exactly one row, got ${rows[k] ? rows[k].length : 0}`), null));
  const s = one('service_session_state'); if (s && (s.current_session_id !== null || s.recent_closed_session_id !== null)) out.push('service_session_state pointers not NULL');
  const p = one('business_day_policy'); if (p && (p.auto_seal_local_time !== null || p.seal_timezone !== 'Europe/Madrid' || p.ticket_reset_on_consolidation_default !== true)) out.push('business_day_policy not at its defaults');
  const l = one('business_day_lifecycle_state'); if (l && ['current_business_day_id', 'current_period_id', 'current_ticket_epoch', 'recent_closed_business_day_id'].some((k) => l[k] !== null)) out.push('business_day_lifecycle_state pointers not NULL');
  const cfg = rows.config || [];
  if (cfg.length !== 1 || cfg[0].chiave !== 'DRIVER_STATO' || cfg[0].valore !== '{}') out.push(`config: expected exactly the DRIVER_STATO lock anchor with '{}', got ${JSON.stringify(cfg)}`);
  return out;
}
function baselineText() { return fs.readFileSync(path.join(ROOT, BASELINE_FILE), 'utf8'); }

module.exports = { SQL, SCHEMAS, CATALOG_DIR, BASELINE_FILE, generate, normalize, fingerprint, compare, parseAcl, load, catalogFromSnapshot, extract, systemRows, systemRowsProblems, baselineText, stable };

if (require.main === module) {
  (async () => {
    const [cmd, a, b] = process.argv.slice(2);
    if (cmd === 'sql') { process.stdout.write(SQL[a] + '\n'); return; }
    if (cmd === 'extract') { await extract(a); console.log('catalog written to', a); return; }
    if (cmd === 'catalog-from-snapshot') {
      const c = catalogFromSnapshot(a); fs.mkdirSync(b, { recursive: true });
      for (const k of ['functions', 'structure', 'extras']) fs.writeFileSync(path.join(b, `${k}.json`), stable(c[k]));
      console.log('catalog written to', b); return;
    }
    if (cmd === 'generate') { fs.writeFileSync(b, generate(load(a))); console.log('baseline written to', b); return; }
    if (cmd === 'verify') {
      const want = generate(load(a || CATALOG_DIR)); const got = fs.readFileSync(b || path.join(ROOT, BASELINE_FILE), 'utf8');
      console.log(JSON.stringify({ identical: want === got, sha256_generated: sha256(want), sha256_file: sha256(got), catalog_fingerprint: fingerprint(load(a || CATALOG_DIR)).sha256 }, null, 1));
      process.exit(want === got ? 0 : 1);
    }
    if (cmd === 'pin') {
      const cat = load(CATALOG_DIR); const text = fs.readFileSync(path.join(ROOT, BASELINE_FILE), 'utf8');
      if (generate(cat) !== text) { console.error('the baseline file is not what the catalog generates: regenerate first'); process.exit(1); }
      const fp = fingerprint(cat);
      const pin = { baseline_file: BASELINE_FILE, baseline_sha256: sha256(Buffer.from(text, 'utf8')), catalog_dir: 'migrations/baseline/catalog_tip138',
        catalog_files_sha256: Object.fromEntries(['functions.json', 'structure.json', 'extras.json'].map((f) => [f, sha256(fs.readFileSync(path.join(CATALOG_DIR, f)))])),
        catalog_fingerprint_sha256: fp.sha256, catalog_fingerprint_sections: fp.sections,
        counts: { functions: cat.functions.length, tables: cat.structure.tables.length, sequences: cat.structure.sequences.length, publications: cat.structure.publications.length, platform_triggers: cat.extras.platform_triggers.length },
        source: 'staging tdikhfeinufaahagmpjz, ledger tip 138, read-only catalog, 2026-09-27; sanitized by catalog-from-snapshot' };
      fs.writeFileSync(path.join(ROOT, 'migrations/baseline/v3_greenfield_baseline_tip138.fingerprint.json'), stable(pin)); console.log(JSON.stringify(pin, null, 1)); return;
    }
    if (cmd === 'fingerprint') { console.log(JSON.stringify(fingerprint(load(a)), null, 1)); return; }
    if (cmd === 'compare') { const d = compare(load(a), load(b)); console.log(JSON.stringify(d, null, 1)); console.error(`${d.length} difference(s)`); process.exit(d.length ? 1 : 0); }
    console.error('usage: v3GreenfieldBaseline.js sql <functions|structure|extras|system_rows> | extract <dir> | catalog-from-snapshot <snapshotDir> <outDir> | generate <catalogDir> <out.sql> | verify [<catalogDir> <baseline.sql>] | fingerprint <dir> | compare <dirA> <dirB>');
    process.exit(2);
  })().catch((e) => { console.error(e.message); process.exit(2); });
}
